"""Remove url and meta_data columns from Raw model

Revision ID: 3d2fe23ad160
Revises: f7c646b7911b
Create Date: 2026-03-12 21:31:45.191005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2fe23ad160'
down_revision: Union[str, Sequence[str], None] = 'f7c646b7911b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('crawl_detail_started_at', sa.DateTime(), nullable=True),
    sa.Column('crawl_detail_ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_raw_in_progress_detail', 'raw', ['crawl_detail_started_at'], unique=False, postgresql_where=sa.text('crawl_detail_started_at IS NOT NULL AND crawl_detail_ended_at IS NULL'))
    op.create_index('ix_raw_pending_detail', 'raw', ['item_id'], unique=False, postgresql_where=sa.text('crawl_detail_started_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_pending_detail', table_name='raw', postgresql_where=sa.text('crawl_detail_started_at IS NULL'))
    op.drop_index('ix_raw_in_progress_detail', table_name='raw', postgresql_where=sa.text('crawl_detail_started_at IS NOT NULL AND crawl_detail_ended_at IS NULL'))
    op.drop_table('raw')
    # ### end Alembic commands ###
