"""Add has_pdf column to Raw model

Revision ID: be88623442e8
Revises: 3d2fe23ad160
Create Date: 2026-03-12 21:45:42.620859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be88623442e8'
down_revision: Union[str, Sequence[str], None] = '3d2fe23ad160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('has_pdf', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw', 'has_pdf')
    # ### end Alembic commands ###
